### ISSUE TITLE
시각화 방안

### ISSUE THREAD

**Issue by choitaedong2** [ClustProject/WSAutoMLModelSelection#4]
2차년도 개발 예정인 시각화 관련하여 Maria DB, Influx DB 연동 할 수 있는 시각화 방안 고려해주시기 바랍니다

1) Influx DB - Grafana 사용 관련하여 Python 기반의 시각화 모델 개발 방안 고려 중입니다

**Comment by SOL-2** [comment]
AutoML 플랫폼 UI 설계 관련하여
데이터 대쉬보드 기능 설계 부분 D3.js 자바스크립트 기반의 시각화 방안 고려중입니다.

**Comment by ricky2634** [comment]
Apache Zepplin을 사용한 시각화 방안 고려 중입니다.
참고 URL 첨부합니다. url : [https://zeppelin.apache.org/](url)

Apache Zeppelin 장점 
- Web 기반의 Notebook 환경을 통한 해결을 위해 만들어진 어플리케이션이며 초심자의 접근성이 뛰어나다.
Web기반의 Notebook 스타일 환경이란 Web에 워드프로세서 처럼 화면에 코드를 작성-실행-결과확인-코드수정을 반복하면서 원하는 결과를 만들어 낼수있는 작업환경을 말한다.
- Zepplin을 활용하여 Web에서 Pyhton, Scala 등의 다양한 언어로 분석 코드를 짤수 있고 결과를 Graph로 시각화하여 볼수 있다.
- Spark뿐만이 아닌 Livy, Cassandra, Lens, SQL 등등의 다른 분석 도구나 데이터 베이스에 접근하여 쿼리하는 것을 쉽게 할수 있는 확장 기능들을 지원한다.
- Zepplin은 한번 연결해 두면 같은 Notebook환경에서 Pyspark 와 SparkR 그리고 Cassandra DB를 한번에 조회하는 등의 일을 편하게 할 수 있다.
- WebSocket을 활용하여 같은 Notebook을 여러 사람이 동시에 편집할수 있는 기능을 제공한다. (협업이 가능하다)

해당 장점들로 인하여 Apache Zeppelin 을 활용한 시각화 방안 고려중입니다.
